# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e70579d7133f911329750a8917fdee78ab6f3cca2942e70a2b055c9a38badf7471f1e25e1e56658e77a7cc6c98804533dae62dd3050d8c7bbc053c8f810327f4

test:
  secret_key_base: c8ef2ddaac3f476efd4f664aa9507022f7379329171236fa0e4c7825223008c0c32f07b4867a2d2f1038758e5b838c614b31f58d2eab3efc6ed880f32a523e08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
